events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen       80;
        server_name  localhost;

        # Главная страница
        location / {
            root   /usr/share/nginx/html;
            index  index.html;
        }

        # Папка с локальными файлами для скачивания
        location /files/ {
            alias /usr/share/nginx/html/files/;
            sendfile on;

            # Заставляем браузер скачивать, а не открывать
            add_header Content-Disposition 'attachment';
        }
    }
}