events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    # Устанавливаем тип по умолчанию как бинарный поток, это тоже намекает браузеру на скачивание
    default_type  application/octet-stream;

    server {
        listen       80;
        server_name  localhost;

        location / {
            # Указываем папку, где лежит файл
            root   /usr/share/nginx/html;
            
            # Делаем ваш файл главным (индексным) для этого пути
            index  Таблицы.xlsx;

            # Хедер, который заставляет браузер не открывать файл, а скачивать
            add_header Content-Disposition 'attachment; filename="Таблицы.xlsx"';
        }
    }
}
